---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: debian-7.8
    run_list:
      - recipe[apt]
  - name: debian-8.1
    run_list:
      - recipe[apt]
  - name: debian-7-0-x64
    driver:
      name: digitalocean
    driver_config:
      region: sfo1
      size: 1gb
    run_list:
      - recipe[apt]

suites:
  - name: default
    run_list:
      - recipe[bcas_reader::default]
    attributes:
