---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: debian-7.6
    run_list:
      - recipe[apt]
  - name: debian-7.7
    run_list:
      - recipe[apt]

suites:
  - name: default
    run_list:
      - recipe[bcas_reader::default]
    attributes:
